service: epic-webhook

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x

functions:
  log:
    handler: handler.log
    events:
      - httpApi:
          path: /api/log
          method: post
